services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase
    ports:
      - "3000:3000"  # React-приложение
      - "5000:5000"  # API-сервер
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # Монтируем init.sql только для чтения
    ports:
      - "5432:5432"  # БД будет доступна на порту 5432

volumes:
  postgres_data:
